#!/usr/bin/python3
"""Unittest for max_integer([..])
"""
import unittest
max_integer = __import__('6-max_integer').max_integer
class TestMaxInteger(unittest.TestCase):
	def test_EmptyList(self):
		self.assertEqual(max_integer([]))
	def test_NegativeNumbers(self):
		self.assertEqual(max_integer([-12, -5, -7, -6]), -5)
	def test_SingleNumber(self):
		self.assertEqual(max_integer([8]), 8)
if __name__ = "__main__":
	unittest.main()
